# journey-theme-build:auto — regenerate with journey-theme-build catppuccin --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#cdd6f4
border-color=#89b4fa
background-color=#1e1e2e