# journey-theme-build:auto — regenerate with journey-theme-build flexoki-light --force
$activeBorderColor = rgb(205EA6)

general {
    col.active_border = $activeBorderColor
}

group {
    col.border_active = $activeBorderColor
}