# journey-theme-build:auto — regenerate with journey-theme-build flexoki-light --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#100F0F
border-color=#205EA6
background-color=#FFFCF0