# journey-theme-build:auto — regenerate with journey-theme-build catppuccin-latte --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#4c4f69
border-color=#1e66f5
background-color=#eff1f5