# journey-theme-build:auto — regenerate with journey-theme-build rose-pine --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#575279
border-color=#56949f
background-color=#faf4ed