# journey-theme-build:auto — regenerate with journey-theme-build retro-82 --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#f6dcac
border-color=#faa968
background-color=#05182e