# journey-theme-build:auto — regenerate with journey-theme-build matte-black --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#bebebe
border-color=#e68e0d
background-color=#121212