# journey-theme-build:auto — regenerate with journey-theme-build hackerman --force
include=~/.local/share/journey/default/mako/core.ini

text-color=#ddf7ff
border-color=#82FB9C
background-color=#0B0C16